spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbcdb
    username: root
    password: 12345
#  security:
#    user:
#      name: habib
#      password: nicat
server:
  port: 9090

#  servlet:
#    context-path: /api
